import type { Metadata } from "next";
import type { Insight, SeoPage } from "@/data/seo";
import { publicConfig } from "@/lib/config";
export const siteUrl = publicConfig.siteUrl;
const absolute = (path: string) => siteUrl ? new URL(path, siteUrl).toString() : undefined;
export function createPageMetadata({ title, description, path = "/" }: { title: string; description: string; path?: string }): Metadata { const url = absolute(path); return { title, description, ...(url ? { alternates: { canonical: url } } : {}), openGraph: { title, description, ...(url ? { url } : {}), siteName: "Shivalik Présenté", locale: "en_IN", type: "website" }, twitter: { card: "summary_large_image", title, description }, robots: { index: true, follow: true } }; }
const urlOrPath = (path: string) => absolute(path) ?? path;
export function websiteSchema() { return { "@context": "https://schema.org", "@type": "WebSite", name: "Shivalik Présenté", url: urlOrPath("/"), description: "Riverfront residences in GIFT City, Gandhinagar." }; }
export function pageSchema(page: SeoPage, path: string, crumbs: { href: string; label: string }[]) { return [{ "@context": "https://schema.org", "@type": "WebPage", name: page.title, description: page.description, url: urlOrPath(path), about: { "@type": "ApartmentComplex", name: "Shivalik Présenté", description: "Riverfront residences in GIFT City, Gandhinagar." } }, breadcrumbSchema(crumbs), { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: page.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }]; }
export function breadcrumbSchema(items: { href: string; label: string }[]) { return { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: items.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.label, item: urlOrPath(item.href) })) }; }
export function articleSchema(article: Insight) { return [{ "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.description, datePublished: article.publishedDate, dateModified: article.updatedDate, mainEntityOfPage: urlOrPath(`/insights/${article.slug}`), author: { "@type": "Organization", name: "Présenté Property Insights" } }, breadcrumbSchema([{ href: "/", label: "Home" }, { href: "/insights", label: "Insights" }, { href: `/insights/${article.slug}`, label: article.title }])]; }
