import type { Metadata } from "next";
import type { Insight, SeoPage } from "@/data/seo";
import { publicConfig } from "@/lib/config";
export const siteUrl = publicConfig.siteUrl;
const absolute = (path: string) => siteUrl ? new URL(path, siteUrl).toString() : undefined;
const keywords = ["Shivalik Présenté", "GIFT City residences", "luxury apartments in GIFT City", "riverfront residences Gandhinagar", "4 BHK GIFT City", "duplex penthouse GIFT City", "luxury real estate Ahmedabad"];
const ogImage = "/images/presente/exterior/presente-exterior-wide.jpeg";
export function createPageMetadata({ title, description, path = "/", type = "website" }: { title: string; description: string; path?: string; type?: "website" | "article" }): Metadata { const url = absolute(path); const image = absolute(ogImage); const socialImage = image ? [{ url: image, width: 1200, height: 630, alt: "Shivalik Présenté, GIFT City" }] : undefined; return { title, description, keywords, authors: [{ name: "Shivalik Présenté" }], creator: "Shivalik Présenté", publisher: "Shivalik Présenté", ...(url ? { alternates: { canonical: url } } : {}), openGraph: { title, description, ...(url ? { url } : {}), ...(socialImage ? { images: socialImage } : {}), siteName: "Shivalik Présenté", locale: "en_IN", type }, twitter: { card: "summary_large_image", title, description, ...(image ? { images: [image] } : {}) }, robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1, "max-video-preview": -1 } } }; }
const urlOrPath = (path: string) => absolute(path) ?? path;
export function websiteSchema() { return { "@context": "https://schema.org", "@type": "WebSite", name: "Shivalik Présenté", url: urlOrPath("/"), description: "Riverfront residences in GIFT City, Gandhinagar." }; }
export function pageSchema(page: SeoPage, path: string, crumbs: { href: string; label: string }[]) { return [{ "@context": "https://schema.org", "@type": "WebPage", name: page.title, description: page.description, url: urlOrPath(path), about: { "@type": "ApartmentComplex", name: "Shivalik Présenté", description: "Riverfront residences in GIFT City, Gandhinagar." } }, breadcrumbSchema(crumbs), { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: page.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }]; }
export function breadcrumbSchema(items: { href: string; label: string }[]) { return { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: items.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.label, item: urlOrPath(item.href) })) }; }
export function articleSchema(article: Insight) { return [{ "@context": "https://schema.org", "@type": "BlogPosting", headline: article.title, description: article.description, datePublished: article.publishedDate, dateModified: article.updatedDate, mainEntityOfPage: urlOrPath(`/insights/${article.slug}`), image: [urlOrPath(ogImage)], author: { "@type": "Organization", name: "Shivalik Présenté" }, publisher: { "@type": "Organization", name: "Shivalik Présenté" } }, breadcrumbSchema([{ href: "/", label: "Home" }, { href: "/insights", label: "Insights" }, { href: `/insights/${article.slug}`, label: article.title }])]; }
